import {
  Injectable,
  BadRequestException,
  NotFoundException,
  ForbiddenException,
  Logger,
  Inject,
  forwardRef,
} from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { CreatePaymentDto } from './dto/payment.dto';
import { MercadoPagoService } from './mercadopago.service';
import { CommissionsService } from '../commissions/commissions.service';
import { AuditService } from '../audit/audit.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PaymentGateway, PaymentStatus } from '../../common/enums';

@Injectable()
export class PaymentsService {
  private readonly logger = new Logger(PaymentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly mercadoPagoService: MercadoPagoService,
    @Inject(forwardRef(() => CommissionsService))
    private readonly commissionsService: CommissionsService,
    @Inject(forwardRef(() => AuditService))
    private readonly auditService: AuditService,
    @Inject(forwardRef(() => NotificationsService))
    private readonly notificationsService: NotificationsService,
  ) {}

  async create(
    dto: CreatePaymentDto,
    user: { id: string; email: string; role: string },
  ) {
    const session = await this.prisma.chargingSession.findUnique({
      where: { id: dto.sessionId },
      include: {
        user: { select: { id: true, email: true } },
        station: { select: { name: true } },
      },
    });

    if (!session) {
      throw new NotFoundException('Charging session not found');
    }

    if (session.userId !== user.id) {
      throw new ForbiddenException('You do not own this session');
    }

    if (session.status !== 'COMPLETED') {
      throw new BadRequestException('Charging session is not completed yet');
    }

    if (Number(session.amount) <= 0) {
      throw new BadRequestException('Session has no amount to charge');
    }

    const existingPayment = await this.prisma.payment.findUnique({
      where: { sessionId: dto.sessionId },
    });

    if (existingPayment) {
      throw new BadRequestException('Payment already exists for this session');
    }

    const description = `Recarga - ${session.station.name}`;
    const payerEmail = user.email || session.user.email;

    let gatewayResult: Record<string, unknown>;

    if (dto.gateway === PaymentGateway.PIX) {
      gatewayResult = await this.mercadoPagoService.createPixPayment(
        Number(session.amount),
        description,
        payerEmail,
      );
    } else if (dto.gateway === PaymentGateway.CREDIT_CARD) {
      if (this.mercadoPagoService.isLive && !dto.cardToken) {
        throw new BadRequestException(
          'A card token generated by Mercado Pago is required',
        );
      }
      gatewayResult = await this.mercadoPagoService.createCreditCardPayment(
        Number(session.amount),
        description,
        payerEmail,
        dto.cardToken || '',
        dto.installments || 1,
        dto.paymentMethodId || 'mastercard',
      );
    } else {
      throw new BadRequestException('Invalid payment gateway');
    }

    const payment = await this.prisma.payment.create({
      data: {
        sessionId: dto.sessionId,
        gateway: dto.gateway,
        externalId: String(gatewayResult.id),
        amount: session.amount,
        status: 'PENDING',
      },
      include: { session: { include: { station: true } } },
    });

    this.logger.log(
      `Payment created: ${payment.id} (${dto.gateway}) - R$${session.amount}`,
    );

    const approvedPayment =
      gatewayResult.status === 'approved'
        ? await this.approvePayment(payment.id, String(gatewayResult.id))
        : payment;

    return {
      payment: {
        id: approvedPayment.id,
        sessionId: approvedPayment.sessionId,
        gateway: approvedPayment.gateway,
        amount: Number(approvedPayment.amount),
        status: approvedPayment.status,
      },
      gateway: {
        ...gatewayResult,
        paymentId: payment.id,
      },
    };
  }

  async findById(
    id: string,
    user?: { id: string; role: string; companyId?: string },
  ): Promise<unknown> {
    const payment = await this.prisma.payment.findUnique({
      where: { id },
      include: {
        session: {
          include: {
            station: { select: { id: true, name: true, companyId: true } },
            user: { select: { id: true, name: true, email: true } },
            charger: { select: { id: true, serialNumber: true } },
          },
        },
        commission: true,
      },
    });

    if (!payment) {
      throw new NotFoundException('Payment not found');
    }

    if (user?.role === 'CUSTOMER' && payment.session?.userId !== user.id) {
      throw new ForbiddenException('You do not own this payment');
    }

    if (
      user?.role === 'OPERATOR' &&
      (!user.companyId ||
        payment.session?.station?.companyId !== user.companyId)
    ) {
      throw new ForbiddenException('You do not have access to this payment');
    }

    if (payment.status === 'PENDING' && payment.externalId) {
      const externalId = String(payment.externalId);
      const externalNumber = Number(externalId);
      const canQueryGateway =
        !this.mercadoPagoService.isLive || Number.isInteger(externalNumber);

      if (canQueryGateway) {
        const gatewayStatus = await this.mercadoPagoService.getPaymentStatus(
          this.mercadoPagoService.isLive ? externalNumber : 0,
        );
        if (gatewayStatus.status === 'approved') {
          await this.approvePayment(payment.id, externalId);
          return this.findById(id, user);
        }
        if (
          gatewayStatus.status === 'rejected' ||
          gatewayStatus.status === 'cancelled'
        ) {
          await this.failPayment(payment.id);
          return this.findById(id, user);
        }
      }
    }

    return payment;
  }

  async findBySession(sessionId: string) {
    return this.prisma.payment.findUnique({
      where: { sessionId },
      include: { commission: true },
    });
  }

  async approvePayment(paymentId: string, externalId?: string) {
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
      include: { session: { include: { station: true } } },
    });

    if (!payment) {
      throw new NotFoundException('Payment not found');
    }

    if (payment.status === 'APPROVED') {
      throw new BadRequestException('Payment is already approved');
    }

    // A payment is only marked as approved after its commission and operator
    // credit have been recorded. A retry can therefore safely complete a
    // previously interrupted approval.
    await this.commissionsService.calculate(paymentId);

    const updatedPayment = await this.prisma.payment.update({
      where: { id: paymentId },
      data: {
        status: 'APPROVED',
        externalId: externalId || payment.externalId,
        paidAt: new Date(),
      },
    });

    this.logger.log(`Payment approved: ${paymentId} - R$${payment.amount}`);

    // Audit log
    try {
      await this.auditService.log({
        userId: payment.session?.userId,
        action: 'PAYMENT_APPROVED',
        entity: 'Payment',
        entityId: paymentId,
        newValue: { amount: payment.amount, status: 'APPROVED' },
      });
    } catch {
      this.logger.warn(`Failed to write audit log for payment ${paymentId}`);
    }

    // Send notification
    try {
      const notif = this.auditService.notifications.paymentApproved(
        payment.session?.userId || '',
        Number(payment.amount),
      );
      await this.notificationsService.create(notif);
    } catch {
      this.logger.warn(`Failed to send notification for payment ${paymentId}`);
    }

    return updatedPayment;
  }

  async failPayment(paymentId: string) {
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
    });
    if (!payment) throw new NotFoundException('Payment not found');

    return this.prisma.payment.update({
      where: { id: paymentId },
      data: { status: 'FAILED' },
    });
  }

  async refundPayment(paymentId: string) {
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
      include: {
        session: { include: { station: true } },
        commission: true,
      },
    });
    if (!payment) throw new NotFoundException('Payment not found');

    if (payment.status !== 'APPROVED') {
      throw new BadRequestException('Only approved payments can be refunded');
    }

    if (this.mercadoPagoService.isLive) {
      const externalId = Number(payment.externalId);
      if (!Number.isInteger(externalId)) {
        throw new BadRequestException(
          'Payment has no valid gateway transaction',
        );
      }
      await this.mercadoPagoService.refundPayment(externalId);
    }

    return this.prisma.client.$transaction(async (tx) => {
      if (payment.commission) {
        const wallet = await tx.wallet.findUnique({
          where: { companyId: payment.session.station.companyId },
        });
        if (!wallet) throw new BadRequestException('Wallet not found');

        await tx.transaction.create({
          data: {
            walletId: wallet.id,
            type: 'DEBIT',
            amount: payment.commission.operatorAmount,
            description: 'Estorno de recarga',
          },
        });
        await tx.wallet.update({
          where: { id: wallet.id },
          data: { balance: { decrement: payment.commission.operatorAmount } },
        });
      }

      return tx.payment.update({
        where: { id: paymentId },
        data: { status: 'REFUNDED' },
      });
    });
  }

  async handleWebhook(data: {
    action?: string;
    data?: { id?: string | number };
    type?: string;
  }) {
    this.logger.log(`Webhook received: ${JSON.stringify(data)}`);

    if (data.type === 'payment' && data.data?.id) {
      const mercadoPagoPaymentId = String(data.data.id);
      const numericId = Number(mercadoPagoPaymentId);

      if (!mercadoPagoPaymentId || Number.isNaN(numericId)) {
        this.logger.warn('Webhook received invalid payment id');
        return { received: true };
      }

      try {
        const mpStatus =
          await this.mercadoPagoService.getPaymentStatus(numericId);

        const payment = await this.prisma.payment.findFirst({
          where: { externalId: mercadoPagoPaymentId },
        });

        if (!payment) {
          this.logger.warn(
            `Payment not found for external ID: ${mercadoPagoPaymentId}`,
          );
          return { received: true };
        }

        switch (mpStatus.status) {
          case 'approved':
            await this.approvePayment(payment.id, mercadoPagoPaymentId);
            break;
          case 'rejected':
          case 'cancelled':
            await this.failPayment(payment.id);
            break;
          default:
            this.logger.log(`Payment ${payment.id} status: ${mpStatus.status}`);
        }
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        this.logger.error(`Error processing webhook: ${message}`);
      }
    }

    return { received: true };
  }

  async getReceipt(
    paymentId: string,
    user?: { id: string; role: string; companyId?: string },
  ) {
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
      include: {
        session: {
          include: {
            station: {
              select: { id: true, name: true, address: true, city: true, state: true, companyId: true },
            },
            user: { select: { id: true, name: true, email: true, phone: true } },
            charger: { select: { id: true, serialNumber: true } },
            connector: { select: { type: true } },
            tariff: { select: { name: true, pricePerKwh: true } },
            vehicle: { select: { brand: true, model: true, plate: true } },
          },
        },
        commission: true,
      },
    });

    if (!payment) {
      throw new NotFoundException('Payment not found');
    }

    if (user?.role === 'CUSTOMER' && payment.session?.userId !== user.id) {
      throw new ForbiddenException('You do not own this payment');
    }

    if (
      user?.role === 'OPERATOR' &&
      (!user.companyId || payment.session?.station?.companyId !== user.companyId)
    ) {
      throw new ForbiddenException('You do not have access to this receipt');
    }

    const station = payment.session?.station;
    const session = payment.session;

    const durationMs = session?.endTime && session?.startTime
      ? new Date(session.endTime).getTime() - new Date(session.startTime).getTime()
      : 0;
    const durationMinutes = Math.round(durationMs / 60000);
    const hours = Math.floor(durationMinutes / 60);
    const minutes = durationMinutes % 60;
    const durationFormatted = hours > 0 ? `${hours}h ${minutes}min` : `${minutes}min`;

    return {
      receiptId: payment.id,
      issuedAt: payment.paidAt || payment.createdAt,
      status: payment.status,
      gateway: payment.gateway,
      externalId: payment.externalId,
      transaction: {
        amount: Number(payment.amount),
        currency: 'BRL',
      },
      station: {
        name: station?.name || 'N/A',
        address: station?.address || 'N/A',
        city: station?.city || 'N/A',
        state: station?.state || 'N/A',
      },
      charger: {
        serialNumber: session?.charger?.serialNumber || 'N/A',
        connectorType: session?.connector?.type || 'N/A',
      },
      tariff: {
        name: session?.tariff?.name || 'N/A',
        pricePerKwh: session?.tariff?.pricePerKwh ? Number(session.tariff.pricePerKwh) : null,
      },
      session: {
        energyKwh: Number(session?.energyKwh || 0),
        duration: durationFormatted,
        startTime: session?.startTime,
        endTime: session?.endTime,
        vehicle: session?.vehicle
          ? { brand: session.vehicle.brand, model: session.vehicle.model, plate: session.vehicle.plate }
          : null,
      },
      user: {
        name: session?.user?.name || 'N/A',
        email: session?.user?.email || 'N/A',
        phone: session?.user?.phone || null,
      },
      commission: payment.commission
        ? {
            percentage: Number(payment.commission.percentage),
            platformAmount: Number(payment.commission.platformAmount),
            operatorAmount: Number(payment.commission.operatorAmount),
          }
        : null,
    };
  }

  async getPaymentsByStatus(
    status: string,
    user?: { id: string; role: string; companyId?: string },
  ) {
    const where: {
      status: string;
      session?: { station: { companyId: string } };
    } = { status };

    if (user?.role === 'OPERATOR') {
      if (!user.companyId) {
        throw new ForbiddenException('Operator has no company associated');
      }
      where.session = { station: { companyId: user.companyId } };
    }

    return this.prisma.payment.findMany({
      where: { ...where, status: status as PaymentStatus },
      include: {
        session: {
          include: {
            user: { select: { id: true, name: true, email: true } },
            station: { select: { id: true, name: true } },
          },
        },
        commission: true,
      },
      orderBy: { createdAt: 'desc' },
    });
  }
}
